# Generated by Django 2.1.2 on 2018-11-17 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electives', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Options',
            fields=[
                ('course_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=40)),
                ('dept', models.CharField(max_length=40)),
            ],
        ),
    ]
