# Generated by Django 2.1.2 on 2018-11-20 02:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electives', '0002_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='choices',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
