# Generated by Django 2.1.2 on 2018-11-21 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electives', '0003_choices_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='choices',
            name='cur_time',
            field=models.CharField(blank=True, default='05:12:35', max_length=8),
        ),
    ]
