# Generated by Django 2.1.2 on 2018-11-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electives', '0005_auto_20181126_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choices',
            name='cur_time',
            field=models.CharField(blank=True, default='14:46:59:538805', max_length=8),
        ),
    ]
