# Generated by Django 2.1.2 on 2018-11-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electives', '0009_auto_20181126_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLogin',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('user_pass', models.CharField(max_length=20)),
            ],
        ),
    ]
