# Generated by Django 2.0.5 on 2018-12-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electives', '0011_timer'),
    ]

    operations = [
        migrations.CreateModel(
            name='allocated',
            fields=[
                ('usn', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('sub', models.CharField(max_length=40)),
            ],
        ),
    ]
