# Generated by Django 2.0.5 on 2018-12-14 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electives', '0013_auto_20181214_0409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choices',
            name='date',
        ),
    ]
